### ISSUE TITLE
"NaN seconds ago" when adding a new review and viewing it immediately

### ISSUE THREAD

**Issue by aybeedee** [aybeedee/movie-web-app#1]
![image](https://github.com/aybeedee/movie-web-app/assets/75930195/d0d82a90-1489-4494-baac-38934fb17536)

**Comment by nesyG** [comment]
Hello, can I help with the issue?

**Comment by aybeedee** [comment]
Hi @nesyG, sure go ahead. You can find the related ui at `frontend/src/pages/MovieDetails.tsx` and the helper function that is likely returning the `NaN` at `frontend/src/lib/utils.ts`

All instructions for setting up the project are present in the `README.md`

Feel free to ask for any other information regarding setup or the issue

**Comment by nesyG** [comment]
Thanks, will get to it!
